services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: shrinkr_user
      POSTGRES_PASSWORD: shrinkr_pass
      POSTGRES_DB: shrinkr_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://shrinkr_user:shrinkr_pass@db:5432/shrinkr_db
      APP_NAME: Shrinkr
      DEBUG: "True"
    depends_on:
      - db
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data:

  