services:
  - type: web
    name: shrinkr-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_SSL
        value: "True"
      - key: APP_NAME
        value: Shrinkr
      - key: BASE_URL
        value: https://shrinkr-api.onrender.com
      - key: DEBUG
        value: "False"